[2022-09-22T07:25:45.896+0000] {processor.py:156} INFO - Started process (PID=261) to work on /opt/airflow/dags/dags.py
[2022-09-22T07:25:45.897+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T07:25:45.897+0000] {logging_mixin.py:117} INFO - [2022-09-22T07:25:45.897+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T07:25:52.087+0000] {processor.py:768} INFO - DAG(s) dict_keys(['tutorial']) retrieved from /opt/airflow/dags/dags.py
[2022-09-22T07:26:03.307+0000] {logging_mixin.py:117} INFO - [2022-09-22T07:26:03.306+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2022-09-22T07:26:03.986+0000] {logging_mixin.py:117} INFO - [2022-09-22T07:26:03.986+0000] {dag.py:3328} INFO - Setting next_dagrun for tutorial to 2022-09-20T00:00:00+00:00, run_after=2022-09-21T00:00:00+00:00
[2022-09-22T07:26:07.860+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 22.133 seconds
[2022-09-22T16:04:55.040+0000] {processor.py:156} INFO - Started process (PID=111) to work on /opt/airflow/dags/dags.py
[2022-09-22T16:04:55.311+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T16:04:55.313+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:04:55.313+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T16:04:55.341+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:04:55.318+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T16:04:55.342+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T16:04:56.669+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 1.639 seconds
[2022-09-22T16:05:44.814+0000] {processor.py:156} INFO - Started process (PID=175) to work on /opt/airflow/dags/dags.py
[2022-09-22T16:05:45.488+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T16:05:45.491+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:05:45.491+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T16:05:45.503+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:05:45.501+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T16:05:45.505+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T16:05:46.473+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 1.671 seconds
[2022-09-22T16:06:16.875+0000] {processor.py:156} INFO - Started process (PID=231) to work on /opt/airflow/dags/dags.py
[2022-09-22T16:06:16.876+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T16:06:16.877+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:06:16.877+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T16:06:16.879+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:06:16.878+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T16:06:16.879+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T16:06:17.098+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.226 seconds
[2022-09-22T16:06:47.364+0000] {processor.py:156} INFO - Started process (PID=281) to work on /opt/airflow/dags/dags.py
[2022-09-22T16:06:47.595+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T16:06:47.596+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:06:47.596+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T16:06:47.598+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:06:47.597+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T16:06:47.598+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T16:06:48.461+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 1.101 seconds
[2022-09-22T16:07:20.051+0000] {processor.py:156} INFO - Started process (PID=331) to work on /opt/airflow/dags/dags.py
[2022-09-22T16:07:20.051+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T16:07:20.052+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:07:20.052+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T16:07:20.055+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:07:20.054+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T16:07:20.056+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T16:07:20.903+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.857 seconds
[2022-09-22T16:07:55.713+0000] {processor.py:156} INFO - Started process (PID=389) to work on /opt/airflow/dags/dags.py
[2022-09-22T16:07:55.953+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T16:07:55.954+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:07:55.954+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T16:07:55.959+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:07:55.958+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T16:07:55.960+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T16:07:56.624+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 1.011 seconds
[2022-09-22T16:08:36.239+0000] {processor.py:156} INFO - Started process (PID=444) to work on /opt/airflow/dags/dags.py
[2022-09-22T16:08:36.429+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T16:08:36.430+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:08:36.430+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T16:08:36.434+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:08:36.432+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T16:08:36.434+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T16:08:37.011+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.776 seconds
[2022-09-22T16:09:07.912+0000] {processor.py:156} INFO - Started process (PID=497) to work on /opt/airflow/dags/dags.py
[2022-09-22T16:09:07.913+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T16:09:07.913+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:09:07.913+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T16:09:07.915+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:09:07.914+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T16:09:07.915+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T16:09:08.611+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.703 seconds
[2022-09-22T16:09:39.300+0000] {processor.py:156} INFO - Started process (PID=549) to work on /opt/airflow/dags/dags.py
[2022-09-22T16:09:39.600+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T16:09:39.601+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:09:39.601+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T16:09:39.603+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:09:39.603+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T16:09:39.604+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T16:09:40.000+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.708 seconds
[2022-09-22T16:10:13.956+0000] {processor.py:156} INFO - Started process (PID=594) to work on /opt/airflow/dags/dags.py
[2022-09-22T16:10:14.113+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T16:10:14.114+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:10:14.113+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T16:10:14.117+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:10:14.115+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T16:10:14.117+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T16:10:14.848+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.895 seconds
[2022-09-22T16:10:46.093+0000] {processor.py:156} INFO - Started process (PID=632) to work on /opt/airflow/dags/dags.py
[2022-09-22T16:10:46.425+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T16:10:46.426+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:10:46.425+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T16:10:46.430+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:10:46.428+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T16:10:46.431+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T16:10:47.371+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 1.288 seconds
[2022-09-22T16:11:19.176+0000] {processor.py:156} INFO - Started process (PID=687) to work on /opt/airflow/dags/dags.py
[2022-09-22T16:11:19.178+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T16:11:19.179+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:11:19.179+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T16:11:19.183+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:11:19.182+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T16:11:19.184+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T16:11:19.578+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.409 seconds
[2022-09-22T16:11:49.886+0000] {processor.py:156} INFO - Started process (PID=739) to work on /opt/airflow/dags/dags.py
[2022-09-22T16:11:50.158+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T16:11:50.159+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:11:50.159+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T16:11:50.162+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:11:50.161+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T16:11:50.162+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T16:11:50.508+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.625 seconds
[2022-09-22T16:12:20.791+0000] {processor.py:156} INFO - Started process (PID=793) to work on /opt/airflow/dags/dags.py
[2022-09-22T16:12:20.792+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T16:12:20.793+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:12:20.793+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T16:12:20.795+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:12:20.794+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T16:12:20.796+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T16:12:21.559+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.771 seconds
[2022-09-22T16:12:52.126+0000] {processor.py:156} INFO - Started process (PID=848) to work on /opt/airflow/dags/dags.py
[2022-09-22T16:12:52.193+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T16:12:52.194+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:12:52.194+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T16:12:52.199+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:12:52.197+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T16:12:52.200+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T16:12:52.407+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.285 seconds
[2022-09-22T16:13:22.494+0000] {processor.py:156} INFO - Started process (PID=904) to work on /opt/airflow/dags/dags.py
[2022-09-22T16:13:22.495+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T16:13:22.495+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:13:22.495+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T16:13:22.497+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:13:22.497+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T16:13:22.498+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T16:13:22.825+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.334 seconds
[2022-09-22T16:14:02.043+0000] {processor.py:156} INFO - Started process (PID=954) to work on /opt/airflow/dags/dags.py
[2022-09-22T16:14:02.340+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T16:14:02.341+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:14:02.341+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T16:14:02.343+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:14:02.343+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T16:14:02.344+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T16:14:03.183+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 1.145 seconds
[2022-09-22T16:14:34.887+0000] {processor.py:156} INFO - Started process (PID=1010) to work on /opt/airflow/dags/dags.py
[2022-09-22T16:14:34.891+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T16:14:34.893+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:14:34.892+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T16:14:34.897+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:14:34.895+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T16:14:34.898+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T16:14:35.063+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.184 seconds
[2022-09-22T16:15:05.976+0000] {processor.py:156} INFO - Started process (PID=1074) to work on /opt/airflow/dags/dags.py
[2022-09-22T16:15:06.048+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T16:15:06.050+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:15:06.050+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T16:15:06.056+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:15:06.053+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T16:15:06.106+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T16:15:06.600+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.641 seconds
[2022-09-22T16:15:43.750+0000] {processor.py:156} INFO - Started process (PID=1121) to work on /opt/airflow/dags/dags.py
[2022-09-22T16:15:43.837+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T16:15:43.837+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:15:43.837+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T16:15:43.839+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:15:43.838+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T16:15:43.840+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T16:15:45.959+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 2.212 seconds
[2022-09-22T16:16:16.313+0000] {processor.py:156} INFO - Started process (PID=1175) to work on /opt/airflow/dags/dags.py
[2022-09-22T16:16:16.315+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T16:16:16.315+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:16:16.315+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T16:16:16.317+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:16:16.317+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T16:16:16.318+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T16:16:16.876+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.581 seconds
[2022-09-22T16:17:39.738+0000] {processor.py:156} INFO - Started process (PID=1212) to work on /opt/airflow/dags/dags.py
[2022-09-22T16:17:39.775+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T16:17:39.777+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:17:39.777+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T16:17:39.782+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:17:39.780+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T16:17:39.783+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T16:17:40.289+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.561 seconds
[2022-09-22T16:18:29.356+0000] {processor.py:156} INFO - Started process (PID=1260) to work on /opt/airflow/dags/dags.py
[2022-09-22T16:18:29.603+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T16:18:29.605+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:18:29.604+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T16:18:29.611+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:18:29.608+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T16:18:29.612+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T16:18:30.671+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 1.323 seconds
[2022-09-22T16:19:00.956+0000] {processor.py:156} INFO - Started process (PID=1315) to work on /opt/airflow/dags/dags.py
[2022-09-22T16:19:01.168+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T16:19:01.169+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:19:01.169+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T16:19:01.172+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:19:01.171+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T16:19:01.173+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T16:19:01.619+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.667 seconds
[2022-09-22T16:19:32.426+0000] {processor.py:156} INFO - Started process (PID=1371) to work on /opt/airflow/dags/dags.py
[2022-09-22T16:19:32.429+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T16:19:32.432+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:19:32.431+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T16:19:32.441+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:19:32.437+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T16:19:32.443+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T16:19:32.797+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.389 seconds
[2022-09-22T16:20:03.134+0000] {processor.py:156} INFO - Started process (PID=1424) to work on /opt/airflow/dags/dags.py
[2022-09-22T16:20:03.378+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T16:20:03.616+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:20:03.616+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T16:20:03.618+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:20:03.617+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T16:20:03.619+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T16:20:04.083+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.953 seconds
[2022-09-22T16:20:35.262+0000] {processor.py:156} INFO - Started process (PID=1480) to work on /opt/airflow/dags/dags.py
[2022-09-22T16:20:35.265+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T16:20:35.268+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:20:35.267+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T16:20:35.277+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:20:35.273+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T16:20:35.279+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T16:20:36.254+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 1.006 seconds
[2022-09-22T16:21:06.725+0000] {processor.py:156} INFO - Started process (PID=1523) to work on /opt/airflow/dags/dags.py
[2022-09-22T16:21:07.250+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T16:21:07.400+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:21:07.400+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T16:21:07.402+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:21:07.402+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T16:21:07.403+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T16:21:09.391+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 2.674 seconds
[2022-09-22T16:21:45.881+0000] {processor.py:156} INFO - Started process (PID=1576) to work on /opt/airflow/dags/dags.py
[2022-09-22T16:21:46.312+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T16:21:46.313+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:21:46.313+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T16:21:46.315+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:21:46.314+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T16:21:46.315+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T16:21:47.357+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 1.481 seconds
[2022-09-22T16:22:26.211+0000] {processor.py:156} INFO - Started process (PID=1630) to work on /opt/airflow/dags/dags.py
[2022-09-22T16:22:26.822+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T16:22:26.825+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:22:26.824+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T16:22:26.834+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:22:26.831+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T16:22:26.836+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T16:22:27.628+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 1.424 seconds
[2022-09-22T16:23:05.011+0000] {processor.py:156} INFO - Started process (PID=1678) to work on /opt/airflow/dags/dags.py
[2022-09-22T16:23:05.452+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T16:23:05.454+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:23:05.454+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T16:23:05.459+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:23:05.457+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T16:23:05.460+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T16:23:06.506+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 1.498 seconds
[2022-09-22T16:23:42.083+0000] {processor.py:156} INFO - Started process (PID=1731) to work on /opt/airflow/dags/dags.py
[2022-09-22T16:23:42.274+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T16:23:42.275+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:23:42.275+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T16:23:42.278+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:23:42.276+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T16:23:42.278+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T16:23:43.456+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 1.378 seconds
[2022-09-22T16:24:23.575+0000] {processor.py:156} INFO - Started process (PID=1738) to work on /opt/airflow/dags/dags.py
[2022-09-22T16:24:23.759+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T16:24:23.761+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:24:23.760+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T16:24:23.765+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:24:23.763+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T16:24:24.077+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T16:24:24.672+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 1.110 seconds
[2022-09-22T16:27:24.915+0000] {processor.py:156} INFO - Started process (PID=1789) to work on /opt/airflow/dags/dags.py
[2022-09-22T16:27:25.209+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T16:27:25.213+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:27:25.212+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T16:27:25.222+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:27:25.219+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T16:27:25.224+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T16:27:26.147+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 1.238 seconds
[2022-09-22T16:27:57.293+0000] {processor.py:156} INFO - Started process (PID=1832) to work on /opt/airflow/dags/dags.py
[2022-09-22T16:27:57.635+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T16:27:57.636+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:27:57.636+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T16:27:57.644+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:27:57.641+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T16:27:57.646+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T16:27:58.302+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 1.012 seconds
[2022-09-22T16:28:30.303+0000] {processor.py:156} INFO - Started process (PID=1885) to work on /opt/airflow/dags/dags.py
[2022-09-22T16:28:30.307+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T16:28:30.310+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:28:30.310+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T16:28:30.321+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:28:30.317+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T16:28:30.322+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T16:28:31.063+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.772 seconds
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               [2022-09-22T16:56:47.725+0000] {processor.py:156} INFO - Started process (PID=74) to work on /opt/airflow/dags/dags.py
[2022-09-22T16:56:47.770+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T16:56:47.771+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:56:47.771+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T16:56:47.841+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:56:47.772+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T16:56:47.842+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T16:56:47.945+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.224 seconds
[2022-09-22T16:57:18.705+0000] {processor.py:156} INFO - Started process (PID=138) to work on /opt/airflow/dags/dags.py
[2022-09-22T16:57:18.706+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T16:57:18.707+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:57:18.706+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T16:57:18.708+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:57:18.708+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T16:57:18.709+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T16:57:18.890+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.188 seconds
[2022-09-22T16:57:49.135+0000] {processor.py:156} INFO - Started process (PID=193) to work on /opt/airflow/dags/dags.py
[2022-09-22T16:57:49.185+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T16:57:49.186+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:57:49.186+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T16:57:49.188+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:57:49.187+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T16:57:49.188+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T16:57:49.365+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.234 seconds
[2022-09-22T16:58:56.125+0000] {processor.py:156} INFO - Started process (PID=249) to work on /opt/airflow/dags/dags.py
[2022-09-22T16:58:56.237+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T16:58:56.240+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:58:56.239+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T16:58:56.251+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:58:56.246+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T16:58:56.253+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T16:58:56.845+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.724 seconds
[2022-09-22T16:59:27.310+0000] {processor.py:156} INFO - Started process (PID=303) to work on /opt/airflow/dags/dags.py
[2022-09-22T16:59:27.310+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T16:59:27.311+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:59:27.311+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T16:59:27.314+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:59:27.313+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T16:59:27.314+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T16:59:27.497+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.193 seconds
[2022-09-22T16:59:57.774+0000] {processor.py:156} INFO - Started process (PID=358) to work on /opt/airflow/dags/dags.py
[2022-09-22T16:59:57.840+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T16:59:57.841+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:59:57.841+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T16:59:57.844+0000] {logging_mixin.py:117} INFO - [2022-09-22T16:59:57.843+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T16:59:57.845+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T16:59:58.088+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.324 seconds
[2022-09-22T17:00:28.122+0000] {processor.py:156} INFO - Started process (PID=418) to work on /opt/airflow/dags/dags.py
[2022-09-22T17:00:28.123+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T17:00:28.124+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:00:28.124+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T17:00:28.129+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:00:28.127+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T17:00:28.130+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T17:00:28.305+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.189 seconds
[2022-09-22T17:00:58.478+0000] {processor.py:156} INFO - Started process (PID=473) to work on /opt/airflow/dags/dags.py
[2022-09-22T17:00:58.571+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T17:00:58.572+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:00:58.572+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T17:00:58.574+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:00:58.573+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T17:00:58.574+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T17:00:58.864+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.389 seconds
[2022-09-22T17:01:29.165+0000] {processor.py:156} INFO - Started process (PID=528) to work on /opt/airflow/dags/dags.py
[2022-09-22T17:01:29.166+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T17:01:29.168+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:01:29.168+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T17:01:29.173+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:01:29.171+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T17:01:29.173+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T17:01:29.358+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.201 seconds
[2022-09-22T17:01:59.751+0000] {processor.py:156} INFO - Started process (PID=581) to work on /opt/airflow/dags/dags.py
[2022-09-22T17:01:59.919+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T17:01:59.920+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:01:59.920+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T17:01:59.922+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:01:59.921+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T17:01:59.922+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T17:02:00.241+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.494 seconds
[2022-09-22T17:02:32.449+0000] {processor.py:156} INFO - Started process (PID=634) to work on /opt/airflow/dags/dags.py
[2022-09-22T17:02:32.451+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T17:02:32.452+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:02:32.452+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T17:02:32.456+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:02:32.455+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T17:02:32.457+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T17:02:33.816+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 1.377 seconds
[2022-09-22T17:03:03.028+0000] {processor.py:156} INFO - Started process (PID=688) to work on /opt/airflow/dags/dags.py
[2022-09-22T17:03:03.030+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T17:03:03.034+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:03:03.033+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T17:03:03.036+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:03:03.035+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T17:03:03.037+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T17:03:03.461+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.439 seconds
[2022-09-22T17:03:34.051+0000] {processor.py:156} INFO - Started process (PID=742) to work on /opt/airflow/dags/dags.py
[2022-09-22T17:03:34.292+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T17:03:34.294+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:03:34.293+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T17:03:34.297+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:03:34.296+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T17:03:34.298+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T17:03:34.613+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.570 seconds
[2022-09-22T17:04:05.284+0000] {processor.py:156} INFO - Started process (PID=797) to work on /opt/airflow/dags/dags.py
[2022-09-22T17:04:05.831+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T17:04:05.832+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:04:05.832+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T17:04:05.836+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:04:05.834+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T17:04:05.836+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T17:04:06.048+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.771 seconds
[2022-09-22T17:04:36.940+0000] {processor.py:156} INFO - Started process (PID=851) to work on /opt/airflow/dags/dags.py
[2022-09-22T17:04:37.083+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T17:04:37.084+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:04:37.084+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T17:04:37.087+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:04:37.085+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T17:04:37.087+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T17:04:37.442+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.506 seconds
[2022-09-22T17:05:07.894+0000] {processor.py:156} INFO - Started process (PID=906) to work on /opt/airflow/dags/dags.py
[2022-09-22T17:05:07.896+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T17:05:07.897+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:05:07.897+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T17:05:07.901+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:05:07.900+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T17:05:07.902+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T17:05:08.114+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.227 seconds
[2022-09-22T17:05:38.225+0000] {processor.py:156} INFO - Started process (PID=970) to work on /opt/airflow/dags/dags.py
[2022-09-22T17:05:38.309+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T17:05:38.309+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:05:38.309+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T17:05:38.312+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:05:38.311+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T17:05:38.312+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T17:05:38.597+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.377 seconds
[2022-09-22T17:06:09.127+0000] {processor.py:156} INFO - Started process (PID=1025) to work on /opt/airflow/dags/dags.py
[2022-09-22T17:06:09.128+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T17:06:09.129+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:06:09.129+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T17:06:09.133+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:06:09.131+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T17:06:09.134+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T17:06:09.799+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.679 seconds
[2022-09-22T17:06:59.385+0000] {processor.py:156} INFO - Started process (PID=1086) to work on /opt/airflow/dags/dags.py
[2022-09-22T17:06:59.920+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T17:06:59.922+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:06:59.921+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T17:06:59.926+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:06:59.924+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T17:06:59.927+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T17:07:16.446+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 17.066 seconds
[2022-09-22T17:08:28.900+0000] {processor.py:156} INFO - Started process (PID=1102) to work on /opt/airflow/dags/dags.py
[2022-09-22T17:08:29.464+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T17:08:29.465+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:08:29.465+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T17:08:29.608+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:08:29.467+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T17:08:29.609+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T17:08:34.023+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 5.127 seconds
[2022-09-22T17:14:26.242+0000] {processor.py:156} INFO - Started process (PID=1138) to work on /opt/airflow/dags/dags.py
[2022-09-22T17:14:26.502+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T17:14:26.504+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:14:26.504+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T17:14:26.510+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:14:26.507+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T17:14:26.511+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T17:14:26.922+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.683 seconds
                                                                                                                                                                                                                                                                                                  [2022-09-22T17:39:38.393+0000] {processor.py:156} INFO - Started process (PID=74) to work on /opt/airflow/dags/dags.py
[2022-09-22T17:39:38.428+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T17:39:38.429+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:39:38.428+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T17:39:38.639+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:39:38.463+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T17:39:38.639+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T17:39:39.837+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 1.580 seconds
[2022-09-22T17:41:15.513+0000] {processor.py:156} INFO - Started process (PID=139) to work on /opt/airflow/dags/dags.py
[2022-09-22T17:41:15.570+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T17:41:15.570+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:41:15.570+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T17:41:15.573+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:41:15.572+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T17:41:15.573+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T17:41:15.830+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.322 seconds
[2022-09-22T17:41:49.713+0000] {processor.py:156} INFO - Started process (PID=191) to work on /opt/airflow/dags/dags.py
[2022-09-22T17:41:49.958+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T17:41:49.960+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:41:49.959+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T17:41:49.968+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:41:49.965+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T17:41:49.969+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T17:41:50.722+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 1.024 seconds
[2022-09-22T17:42:24.977+0000] {processor.py:156} INFO - Started process (PID=246) to work on /opt/airflow/dags/dags.py
[2022-09-22T17:42:25.311+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T17:42:25.312+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:42:25.312+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T17:42:25.315+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:42:25.314+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T17:42:25.316+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T17:42:26.426+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 1.457 seconds
[2022-09-22T17:43:17.716+0000] {processor.py:156} INFO - Started process (PID=301) to work on /opt/airflow/dags/dags.py
[2022-09-22T17:43:18.013+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T17:43:18.014+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:43:18.014+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T17:43:18.018+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:43:18.017+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T17:43:18.019+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T17:43:18.712+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 1.002 seconds
[2022-09-22T17:43:51.097+0000] {processor.py:156} INFO - Started process (PID=354) to work on /opt/airflow/dags/dags.py
[2022-09-22T17:43:51.099+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T17:43:51.100+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:43:51.100+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T17:43:51.104+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:43:51.103+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T17:43:51.105+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T17:43:51.900+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.810 seconds
[2022-09-22T17:44:22.806+0000] {processor.py:156} INFO - Started process (PID=398) to work on /opt/airflow/dags/dags.py
[2022-09-22T17:44:23.137+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T17:44:23.138+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:44:23.138+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T17:44:23.141+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:44:23.140+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T17:44:23.141+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T17:44:24.382+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 1.580 seconds
[2022-09-22T17:44:54.947+0000] {processor.py:156} INFO - Started process (PID=451) to work on /opt/airflow/dags/dags.py
[2022-09-22T17:44:55.645+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T17:44:55.647+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:44:55.647+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T17:44:55.652+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:44:55.650+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T17:44:55.653+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T17:44:56.296+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 1.354 seconds
[2022-09-22T17:45:26.947+0000] {processor.py:156} INFO - Started process (PID=505) to work on /opt/airflow/dags/dags.py
[2022-09-22T17:45:26.948+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T17:45:26.949+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:45:26.949+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T17:45:26.953+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:45:26.951+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T17:45:26.953+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T17:45:28.194+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 1.253 seconds
[2022-09-22T17:45:58.396+0000] {processor.py:156} INFO - Started process (PID=560) to work on /opt/airflow/dags/dags.py
[2022-09-22T17:45:58.580+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T17:45:58.582+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:45:58.582+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T17:45:58.593+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:45:58.588+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T17:45:58.594+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T17:45:58.974+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.591 seconds
[2022-09-22T17:46:29.731+0000] {processor.py:156} INFO - Started process (PID=612) to work on /opt/airflow/dags/dags.py
[2022-09-22T17:46:30.139+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T17:46:30.141+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:46:30.140+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T17:46:30.147+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:46:30.145+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T17:46:30.149+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T17:46:31.729+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 2.003 seconds
[2022-09-22T17:47:01.868+0000] {processor.py:156} INFO - Started process (PID=666) to work on /opt/airflow/dags/dags.py
[2022-09-22T17:47:01.869+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T17:47:01.870+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:47:01.870+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T17:47:01.873+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:47:01.872+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T17:47:01.874+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T17:47:02.440+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.576 seconds
[2022-09-22T17:47:33.442+0000] {processor.py:156} INFO - Started process (PID=721) to work on /opt/airflow/dags/dags.py
[2022-09-22T17:47:33.844+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T17:47:33.847+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:47:33.846+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T17:47:33.854+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:47:33.852+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T17:47:33.856+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T17:47:39.037+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 5.603 seconds
[2022-09-22T17:48:09.094+0000] {processor.py:156} INFO - Started process (PID=776) to work on /opt/airflow/dags/dags.py
[2022-09-22T17:48:09.171+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T17:48:09.172+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:48:09.172+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T17:48:09.175+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:48:09.174+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T17:48:09.176+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T17:48:13.971+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 4.882 seconds
[2022-09-22T17:48:44.391+0000] {processor.py:156} INFO - Started process (PID=822) to work on /opt/airflow/dags/dags.py
[2022-09-22T17:48:44.653+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T17:48:44.655+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:48:44.655+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T17:48:44.667+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:48:44.664+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T17:48:44.669+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T17:48:45.428+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 1.054 seconds
[2022-09-22T17:49:27.962+0000] {processor.py:156} INFO - Started process (PID=878) to work on /opt/airflow/dags/dags.py
[2022-09-22T17:49:28.145+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T17:49:28.147+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:49:28.147+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T17:49:28.157+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:49:28.153+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T17:49:28.158+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T17:49:29.528+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 1.576 seconds
[2022-09-22T17:49:59.633+0000] {processor.py:156} INFO - Started process (PID=933) to work on /opt/airflow/dags/dags.py
[2022-09-22T17:49:59.812+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T17:49:59.814+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:49:59.813+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T17:49:59.817+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:49:59.816+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T17:49:59.818+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T17:50:02.635+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 3.006 seconds
[2022-09-22T17:50:43.554+0000] {processor.py:156} INFO - Started process (PID=957) to work on /opt/airflow/dags/dags.py
[2022-09-22T17:50:44.110+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T17:50:44.110+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:50:44.110+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T17:50:44.113+0000] {logging_mixin.py:117} INFO - [2022-09-22T17:50:44.112+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T17:50:44.113+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:13:31.248+0000] {processor.py:156} INFO - Started process (PID=91) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:13:31.298+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:13:31.299+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:13:31.298+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:13:31.443+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:13:31.300+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:13:31.444+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:13:31.560+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.316 seconds
[2022-09-22T19:14:01.920+0000] {processor.py:156} INFO - Started process (PID=146) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:14:01.922+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:14:01.924+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:14:01.923+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:14:01.929+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:14:01.927+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:14:01.930+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:14:02.034+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.120 seconds
[2022-09-22T19:14:32.265+0000] {processor.py:156} INFO - Started process (PID=201) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:14:32.332+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:14:32.334+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:14:32.334+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:14:32.338+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:14:32.337+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:14:32.339+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:14:32.658+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.396 seconds
[2022-09-22T19:15:08.844+0000] {processor.py:156} INFO - Started process (PID=260) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:15:08.859+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:15:08.860+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:15:08.860+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:15:08.863+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:15:08.862+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:15:08.864+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:15:09.141+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.302 seconds
[2022-09-22T19:15:39.804+0000] {processor.py:156} INFO - Started process (PID=303) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:15:39.806+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:15:39.808+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:15:39.808+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:15:40.101+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:15:39.811+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:15:40.101+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:15:40.349+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.554 seconds
[2022-09-22T19:16:10.899+0000] {processor.py:156} INFO - Started process (PID=359) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:16:11.012+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:16:11.012+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:16:11.012+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:16:11.014+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:16:11.014+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:16:11.015+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:16:11.176+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.280 seconds
[2022-09-22T19:16:41.569+0000] {processor.py:156} INFO - Started process (PID=423) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:16:41.607+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:16:41.608+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:16:41.608+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:16:41.611+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:16:41.610+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:16:41.612+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:16:41.747+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.181 seconds
[2022-09-22T19:17:11.860+0000] {processor.py:156} INFO - Started process (PID=474) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:17:11.860+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:17:11.861+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:17:11.861+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:17:11.863+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:17:11.862+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:17:11.863+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:17:11.929+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.073 seconds
[2022-09-22T19:17:42.625+0000] {processor.py:156} INFO - Started process (PID=538) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:17:42.637+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:17:42.639+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:17:42.638+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:17:42.642+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:17:42.640+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:17:42.642+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:17:42.703+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.084 seconds
[2022-09-22T19:18:12.999+0000] {processor.py:156} INFO - Started process (PID=593) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:18:13.000+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:18:13.000+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:18:13.000+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:18:13.002+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:18:13.001+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:18:13.002+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:18:13.122+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.128 seconds
[2022-09-22T19:18:43.527+0000] {processor.py:156} INFO - Started process (PID=657) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:18:43.705+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:18:43.705+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:18:43.705+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:18:43.707+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:18:43.706+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:18:43.708+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:18:43.915+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.391 seconds
[2022-09-22T19:19:14.247+0000] {processor.py:156} INFO - Started process (PID=712) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:19:14.248+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:19:14.249+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:19:14.249+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:19:14.251+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:19:14.250+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:19:14.252+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:19:14.355+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.113 seconds
[2022-09-22T19:19:44.383+0000] {processor.py:156} INFO - Started process (PID=776) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:19:44.485+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:19:44.489+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:19:44.488+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:19:44.504+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:19:44.501+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:19:44.505+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:19:44.604+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.226 seconds
[2022-09-22T19:20:14.757+0000] {processor.py:156} INFO - Started process (PID=831) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:20:14.793+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:20:14.796+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:20:14.796+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:20:14.806+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:20:14.802+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:20:14.808+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:20:14.895+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.146 seconds
[2022-09-22T19:20:45.426+0000] {processor.py:156} INFO - Started process (PID=895) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:20:45.427+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:20:45.428+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:20:45.428+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:20:45.430+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:20:45.429+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:20:45.431+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:20:45.482+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.060 seconds
[2022-09-22T19:21:16.162+0000] {processor.py:156} INFO - Started process (PID=951) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:21:16.326+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:21:16.328+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:21:16.327+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:21:16.333+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:21:16.331+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:21:16.334+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:21:16.723+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.568 seconds
[2022-09-22T19:21:47.192+0000] {processor.py:156} INFO - Started process (PID=1006) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:21:47.194+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:21:47.195+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:21:47.195+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:21:47.199+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:21:47.197+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:21:47.199+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:21:47.757+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.572 seconds
[2022-09-22T19:22:17.798+0000] {processor.py:156} INFO - Started process (PID=1070) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:22:17.851+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:22:17.854+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:22:17.853+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:22:17.861+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:22:17.859+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:22:17.863+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:22:18.162+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.370 seconds
[2022-09-22T19:22:48.614+0000] {processor.py:156} INFO - Started process (PID=1125) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:22:48.615+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:22:48.616+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:22:48.616+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:22:48.618+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:22:48.617+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:22:48.619+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:22:48.860+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.254 seconds
[2022-09-22T19:23:19.617+0000] {processor.py:156} INFO - Started process (PID=1180) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:23:19.721+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:23:19.722+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:23:19.722+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:23:19.724+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:23:19.724+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:23:19.725+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:23:19.993+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.386 seconds
[2022-09-22T19:23:50.978+0000] {processor.py:156} INFO - Started process (PID=1241) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:23:51.175+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:23:51.176+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:23:51.176+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:23:51.178+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:23:51.178+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:23:51.179+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:23:51.363+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.389 seconds
[2022-09-22T19:24:21.673+0000] {processor.py:156} INFO - Started process (PID=1299) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:24:21.674+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:24:21.675+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:24:21.674+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:24:21.677+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:24:21.676+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:24:21.677+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:24:21.808+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.138 seconds
[2022-09-22T19:24:53.766+0000] {processor.py:156} INFO - Started process (PID=1354) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:24:53.800+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:24:53.800+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:24:53.800+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:24:53.804+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:24:53.802+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:24:53.804+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:24:54.159+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.397 seconds
[2022-09-22T19:25:24.404+0000] {processor.py:156} INFO - Started process (PID=1418) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:25:24.437+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:25:24.438+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:25:24.438+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:25:24.441+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:25:24.440+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:25:24.441+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:25:24.619+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.220 seconds
[2022-09-22T19:25:55.311+0000] {processor.py:156} INFO - Started process (PID=1473) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:25:55.313+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:25:55.314+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:25:55.313+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:25:55.318+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:25:55.316+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:25:55.318+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:25:55.503+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.198 seconds
[2022-09-22T19:26:25.806+0000] {processor.py:156} INFO - Started process (PID=1528) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:26:25.854+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:26:25.854+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:26:25.854+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:26:25.857+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:26:25.856+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:26:25.857+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:26:25.964+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.163 seconds
[2022-09-22T19:26:55.991+0000] {processor.py:156} INFO - Started process (PID=1592) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:26:55.992+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:26:55.993+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:26:55.993+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:26:55.997+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:26:55.996+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:26:55.998+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:26:56.202+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.217 seconds
[2022-09-22T19:27:26.952+0000] {processor.py:156} INFO - Started process (PID=1647) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:27:26.972+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:27:26.973+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:27:26.973+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:27:26.976+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:27:26.975+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:27:26.977+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:27:27.181+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.235 seconds
[2022-09-22T19:27:57.564+0000] {processor.py:156} INFO - Started process (PID=1712) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:27:57.565+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:27:57.567+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:27:57.566+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:27:57.570+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:27:57.569+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:27:57.570+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:27:57.629+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.070 seconds
[2022-09-22T19:28:31.326+0000] {processor.py:156} INFO - Started process (PID=1754) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:28:31.577+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:28:31.581+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:28:31.581+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:28:31.585+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:28:31.584+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:28:31.586+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:28:31.993+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.672 seconds
[2022-09-22T19:29:05.873+0000] {processor.py:156} INFO - Started process (PID=1798) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:29:06.113+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:29:06.114+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:29:06.113+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:29:06.116+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:29:06.115+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:29:06.117+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:29:06.460+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.591 seconds
[2022-09-22T19:29:36.635+0000] {processor.py:156} INFO - Started process (PID=1853) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:29:36.637+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:29:36.638+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:29:36.638+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:29:36.644+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:29:36.642+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:29:36.645+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:29:36.839+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.213 seconds
[2022-09-22T19:30:09.019+0000] {processor.py:156} INFO - Started process (PID=1894) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:30:09.282+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:30:09.283+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:30:09.283+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:30:09.286+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:30:09.284+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:30:09.286+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:30:10.065+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 1.050 seconds
[2022-09-22T19:30:44.809+0000] {processor.py:156} INFO - Started process (PID=1950) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:30:45.011+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:30:45.012+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:30:45.012+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:30:45.014+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:30:45.013+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:30:45.014+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:30:46.415+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 1.608 seconds
[2022-09-22T19:31:23.227+0000] {processor.py:156} INFO - Started process (PID=1997) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:31:23.999+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:31:24.001+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:31:24.001+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:31:24.007+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:31:24.004+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:31:24.008+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:31:28.940+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 6.257 seconds
[2022-09-22T19:32:42.807+0000] {processor.py:156} INFO - Started process (PID=2050) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:32:43.069+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:32:43.070+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:32:43.069+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:32:43.073+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:32:43.071+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:32:43.073+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:32:43.936+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 1.134 seconds
[2022-09-22T19:33:58.638+0000] {processor.py:156} INFO - Started process (PID=2090) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:33:58.717+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:33:58.718+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:33:58.718+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:33:58.723+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:33:58.721+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:33:58.724+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:33:59.459+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.836 seconds
[2022-09-22T19:34:31.763+0000] {processor.py:156} INFO - Started process (PID=2144) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:34:33.013+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:34:33.151+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:34:33.151+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:34:33.154+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:34:33.153+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:34:33.155+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:34:36.626+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 4.627 seconds
[2022-09-22T19:35:18.093+0000] {processor.py:156} INFO - Started process (PID=2188) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:35:18.422+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:35:18.424+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:35:18.423+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:35:18.428+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:35:18.426+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:35:18.429+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:35:18.856+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.769 seconds
[2022-09-22T19:35:49.393+0000] {processor.py:156} INFO - Started process (PID=2243) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:35:49.394+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:35:49.395+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:35:49.395+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:35:49.398+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:35:49.397+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:35:49.398+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:35:49.724+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.336 seconds
[2022-09-22T19:36:22.773+0000] {processor.py:156} INFO - Started process (PID=2297) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:36:23.005+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:36:23.005+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:36:23.005+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:36:23.008+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:36:23.007+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:36:23.008+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:36:23.852+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 1.083 seconds
[2022-09-22T19:36:55.586+0000] {processor.py:156} INFO - Started process (PID=2351) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:36:55.589+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:36:55.592+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:36:55.591+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:36:55.599+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:36:55.597+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:36:55.600+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:36:57.653+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 2.082 seconds
[2022-09-22T19:37:27.883+0000] {processor.py:156} INFO - Started process (PID=2406) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:37:28.181+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:37:28.183+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:37:28.183+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:37:28.191+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:37:28.187+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:37:28.192+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:37:28.570+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.702 seconds
[2022-09-22T19:37:59.623+0000] {processor.py:156} INFO - Started process (PID=2461) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:37:59.626+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:37:59.629+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:37:59.629+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:37:59.634+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:37:59.632+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:37:59.635+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:37:59.922+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.315 seconds
[2022-09-22T19:38:29.985+0000] {processor.py:156} INFO - Started process (PID=2514) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:38:30.379+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:38:30.380+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:38:30.380+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:38:30.385+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:38:30.384+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:38:30.386+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:38:31.232+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 1.258 seconds
[2022-09-22T19:39:01.413+0000] {processor.py:156} INFO - Started process (PID=2569) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:39:01.416+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:39:01.419+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:39:01.418+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:39:01.425+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:39:01.423+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:39:01.426+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:39:02.166+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.768 seconds
[2022-09-22T19:39:33.394+0000] {processor.py:156} INFO - Started process (PID=2622) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:39:33.814+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:39:33.818+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:39:33.817+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:39:33.832+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:39:33.828+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:39:33.833+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:39:35.623+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 2.237 seconds
[2022-09-22T19:40:06.633+0000] {processor.py:156} INFO - Started process (PID=2677) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:40:07.047+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:40:07.049+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:40:07.048+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:40:07.053+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:40:07.051+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:40:07.054+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:40:08.180+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 1.555 seconds
[2022-09-22T19:40:38.482+0000] {processor.py:156} INFO - Started process (PID=2732) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:40:38.483+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:40:38.484+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:40:38.484+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:40:38.487+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:40:38.486+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:40:38.487+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:40:39.026+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.547 seconds
[2022-09-22T19:41:12.632+0000] {processor.py:156} INFO - Started process (PID=2787) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:41:13.034+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:41:13.035+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:41:13.035+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:41:13.039+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:41:13.038+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:41:13.040+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:41:16.097+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 3.468 seconds
[2022-09-22T19:41:46.685+0000] {processor.py:156} INFO - Started process (PID=2840) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:41:46.967+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:41:46.968+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:41:46.968+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:41:46.972+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:41:46.970+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:41:46.972+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:41:48.240+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 1.557 seconds
[2022-09-22T19:42:20.500+0000] {processor.py:156} INFO - Started process (PID=2888) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:42:20.937+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:42:20.938+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:42:20.938+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:42:20.941+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:42:20.940+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:42:20.941+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:42:23.031+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 2.549 seconds
[2022-09-22T19:42:53.427+0000] {processor.py:156} INFO - Started process (PID=2941) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:42:53.556+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:42:53.559+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:42:53.558+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:42:53.569+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:42:53.565+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:42:53.572+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:42:54.191+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.775 seconds
[2022-09-22T19:43:24.542+0000] {processor.py:156} INFO - Started process (PID=3005) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:43:24.543+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:43:24.543+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:43:24.543+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:43:24.546+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:43:24.545+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:43:24.546+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:43:24.853+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.314 seconds
[2022-09-22T19:43:55.241+0000] {processor.py:156} INFO - Started process (PID=3060) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:43:55.280+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:43:55.281+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:43:55.281+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:43:55.285+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:43:55.284+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:43:55.286+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:43:55.666+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.434 seconds
[2022-09-22T19:44:26.361+0000] {processor.py:156} INFO - Started process (PID=3115) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:44:26.365+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:44:26.370+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:44:26.370+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:44:26.377+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:44:26.374+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:44:26.378+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:44:26.944+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.592 seconds
[2022-09-22T19:45:02.334+0000] {processor.py:156} INFO - Started process (PID=3170) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:45:02.473+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:45:02.479+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:45:02.478+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:45:02.488+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:45:02.484+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:45:02.490+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:45:03.008+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 0.687 seconds
[2022-09-22T19:45:34.144+0000] {processor.py:156} INFO - Started process (PID=3225) to work on /opt/airflow/dags/dags.py
[2022-09-22T19:45:34.145+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2022-09-22T19:45:34.146+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:45:34.146+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2022-09-22T19:45:34.151+0000] {logging_mixin.py:117} INFO - [2022-09-22T19:45:34.149+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 65
    create_table >> insert_data
               ^
SyntaxError: invalid syntax
[2022-09-22T19:45:34.151+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2022-09-22T19:45:35.434+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/dags.py took 1.297 seconds
